# Setup
title:            Empirical Research in Social Sciences
tagline:          'ERiSS'
description:      'A foundational course for aspiring social scientific researchers.'
url:              https://zhang-feiran.github.io
baseurl:          '/ERiSS'
paginate:         10
markdown:         kramdown

# About and contact
author:
  name:           'Feiran Zhang'          

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-optional-front-matter

# Custom vars
# version:          3.0.0
