# Setup
title:            Empirical Research in Social Sciences
tagline:          'ERiSS'
description:      'A foundational course for aspiring social scientific researchers.'
url:              https://zhang-feiran.github.io/ERiSS/
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Feiran Zhang'
  url:            

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
