# Setup
title:            Empirical Research in Social Sciences
tagline:          'ERiSS'
description:      'A brazen two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://zhang-feiran.github.io/ERiSS
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Feiran Zhang'
  url:            

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
